import React, { useState } from "react";
import { MessageSquarePlus, Edit, Sparkles, Check, Flame, RefreshCw } from "lucide-react";
import { Clip, VideoProject, Subtitle } from "../types";

interface CaptionTranscriberProps {
  selectedProject: VideoProject;
  activeClip: Clip | null;
  onUpdateClip: (fields: Partial<Clip>) => void;
  onPostSuggestedDetails: (caption: string, tags: string[]) => void;
}

export default function CaptionTranscriber({
  selectedProject,
  activeClip,
  onUpdateClip,
  onPostSuggestedDetails
}: CaptionTranscriberProps) {
  const [transcribing, setTranscribing] = useState(false);
  const [generatingCaption, setGeneratingCaption] = useState(false);
  const [editingSubId, setEditingSubId] = useState<string | null>(null);
  const [editVal, setEditVal] = useState("");
  const [burnedStyle, setBurnedStyle] = useState("yellow-pop");

  // Summary generation states
  const [summaryFormat, setSummaryFormat] = useState<"paragraph" | "bullets">("bullets");
  const [generatedSummary, setGeneratedSummary] = useState("");
  const [summarizing, setSummarizing] = useState(false);
  const [copiedSummary, setCopiedSummary] = useState(false);

  if (!activeClip) {
    return (
      <div className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl p-6 shadow-xl flex items-center justify-center text-center h-48">
        <p className="text-xs text-slate-400">Select a clip to transcribe speech and generate caption copy.</p>
      </div>
    );
  }

  // Trigger ASMR/Whisper Transcription via Backend proxying to server-side Gemini 3.5 Flash
  const triggerTranscription = async () => {
    setTranscribing(true);
    try {
      const res = await fetch(`/api/projects/${selectedProject.id}/clips/${activeClip.id}/transcribe`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          videoTitle: selectedProject.title,
          clipContext: activeClip.name
        })
      });
      if (res.ok) {
        const data = await res.json();
        onUpdateClip({ subtitles: data.subtitles });
      }
    } catch (e) {
      console.error(e);
    } finally {
      setTranscribing(false);
    }
  };

  // Trigger copywrite suggestions using AI models
  const generateSocialCopy = async () => {
    setGeneratingCaption(true);
    try {
      const res = await fetch(`/api/posts/suggest-captions`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: selectedProject.title,
          clipName: activeClip.name,
          category: activeClip.backgroundMusic
        })
      });
      if (res.ok) {
        const data = await res.json();
        onPostSuggestedDetails(data.caption, data.hashtags);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setGeneratingCaption(false);
    }
  };

  // Summarize the transcript generated by the ASR service
  const handleSummarizeTranscript = async () => {
    if (!activeClip.subtitles || activeClip.subtitles.length === 0) return;
    setSummarizing(true);
    setGeneratedSummary("");

    const fullTranscript = activeClip.subtitles.map(s => s.text).join(" ");
    try {
      const res = await fetch("/api/transcript/summary", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          transcript: fullTranscript,
          format: summaryFormat
        })
      });
      if (res.ok) {
        const data = await res.json();
        setGeneratedSummary(data.summary);
      }
    } catch (e) {
      console.error(e);
      setGeneratedSummary("Failed to generate summary.");
    } finally {
      setSummarizing(false);
    }
  };

  const handleCopySummary = () => {
    if (!generatedSummary) return;
    navigator.clipboard.writeText(generatedSummary);
    setCopiedSummary(true);
    setTimeout(() => setCopiedSummary(false), 2000);
  };

  const handleApplySummary = () => {
    if (!generatedSummary) return;
    onPostSuggestedDetails(generatedSummary, ["highlights", "shorts", "reels", "insights", "education"]);
  };

  // Save modified subtitles
  const saveSubtitleEdit = (subId: string) => {
    const updated = activeClip.subtitles.map((sub) => {
      if (sub.id === subId) {
        return { ...sub, text: editVal };
      }
      return sub;
    });
    onUpdateClip({ subtitles: updated });
    setEditingSubId(null);
  };

  return (
    <div id="caption-transcriber-widget" className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl p-6 shadow-xl h-full">
      <div className="flex items-center justify-between mb-5">
        <div>
          <h2 className="text-sm font-bold text-white font-display">Auto Captions & Social Copy</h2>
          <p className="text-xs text-slate-400">Transcribe speech & generate optimized tags using Gemini</p>
        </div>
        <Flame className="w-5 h-5 text-amber-400 animate-pulse" />
      </div>

      <div className="space-y-5">
        {/* Whisper Triggers & Font Theme Selectors */}
        <div className="flex flex-col sm:flex-row gap-3">
          <button
            id="btn-trigger-asr"
            onClick={triggerTranscription}
            disabled={transcribing}
            className="flex-1 flex items-center justify-center gap-2 bg-indigo-600 hover:bg-indigo-501 text-white font-bold text-xs py-2 px-4 rounded-xl transition-all shadow-md shadow-indigo-600/10 cursor-pointer disabled:bg-slate-800 disabled:text-slate-400"
          >
            {transcribing ? (
              <>
                <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                <span>ASR transcribing...</span>
              </>
            ) : (
              <>
                <MessageSquarePlus className="w-3.5 h-3.5" />
                <span>Whisper Auto-Transcribe</span>
              </>
            )}
          </button>

          <div className="flex items-center gap-2 bg-black/40 px-3 py-1.5 rounded-xl border border-white/10">
            <span className="text-[11px] text-slate-400 whitespace-nowrap">Subtitle Style:</span>
            <select
              id="subtitles-font-tag"
              value={burnedStyle}
              onChange={(e) => setBurnedStyle(e.target.value)}
              className="text-xs font-bold text-white bg-transparent outline-none focus:outline-none cursor-pointer"
            >
              <option value="yellow-pop" className="bg-slate-900 text-white">TikTok Bold Yellow</option>
              <option value="white-shadow" className="bg-slate-900 text-white">Clean White Shadow</option>
              <option value="subtle-lower" className="bg-slate-900 text-white">Subtle Lower-Third Cased</option>
            </select>
          </div>
        </div>

        {/* Burned-in subtitles editor list */}
        <div className="space-y-2">
          <h3 className="text-[10px] font-bold text-slate-400 uppercase tracking-wider font-display">Burned-in Captions (Editable)</h3>
          {activeClip.subtitles.length === 0 ? (
            <div className="text-center py-6 bg-white/5 rounded-xl border border-dashed border-white/10">
              <p className="text-xs text-slate-400">Click auto transmit above to hear and map subtitle overlays.</p>
            </div>
          ) : (
            <div className="max-h-48 overflow-y-auto space-y-2 border border-white/10 rounded-xl p-2 bg-black/30">
              {activeClip.subtitles.map((sub) => {
                const isEditing = editingSubId === sub.id;
                return (
                  <div key={sub.id} className="flex items-center justify-between p-2 rounded-lg bg-white/5 border border-white/10">
                    <div className="flex-1 mr-2">
                      <span className="text-[9px] font-mono bg-indigo-500/10 text-indigo-300 px-1 py-0.5 rounded mr-2">
                        {sub.startTime} - {sub.endTime}
                      </span>
                      {isEditing ? (
                        <input
                          id={`input-sub-edit-${sub.id}`}
                          type="text"
                          value={editVal}
                          onChange={(e) => setEditVal(e.target.value)}
                          className="text-xs px-1.5 py-0.5 bg-black/60 border border-white/10 text-white rounded focus:outline-hidden"
                          autoFocus
                        />
                      ) : (
                        <span className="text-xs text-slate-200 font-medium">{sub.text}</span>
                      )}
                    </div>

                    <div>
                      {isEditing ? (
                        <button
                          id={`btn-save-sub-${sub.id}`}
                          onClick={() => saveSubtitleEdit(sub.id)}
                          className="text-emerald-400 hover:text-emerald-300 p-1"
                        >
                          <Check className="w-3.5 h-3.5" />
                        </button>
                      ) : (
                        <button
                          id={`btn-edit-sub-${sub.id}`}
                          onClick={() => {
                            setEditingSubId(sub.id);
                            setEditVal(sub.text);
                          }}
                          className="text-slate-400 hover:text-indigo-400 p-1"
                        >
                          <Edit className="w-3.5 h-3.5" />
                        </button>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* AI Social Caption Generator */}
        <div className="bg-indigo-500/10 p-4 rounded-2xl border border-indigo-500/20 space-y-2.5 shadow-sm">
          <div className="flex justify-between items-center">
            <div>
              <h4 className="text-xs font-bold text-white flex items-center gap-1 font-display">
                <Sparkles className="w-3.5 h-3.5 text-indigo-400" />
                <span>AI Social Copy (Hooks)</span>
              </h4>
              <p className="text-[10px] text-slate-400">Auto-generate captions and reels descriptions</p>
            </div>
            <button
              id="btn-social-copy-generate"
              onClick={generateSocialCopy}
              disabled={generatingCaption}
              className="px-3 py-1.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg text-[10px] font-bold flex items-center gap-1 transition-all shadow-md shadow-indigo-600/25 cursor-pointer disabled:bg-slate-800 disabled:text-slate-400"
            >
              {generatingCaption ? "Thinking..." : "Generate Description"}
            </button>
          </div>
        </div>

        {/* Video Transcript Summary & Key Talking Points Extractor */}
        <div className="bg-white/5 p-4 rounded-2xl border border-white/10 space-y-3 shadow-md">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2.5">
            <div>
              <h4 className="text-xs font-bold text-white flex items-center gap-1.5 font-display">
                <MessageSquarePlus className="w-3.5 h-3.5 text-emerald-400" />
                <span>ASR Transcript Summarizer</span>
              </h4>
              <p className="text-[10px] text-slate-400">Condense ASR dialogue into social previews or bullets</p>
            </div>
            
            <div className="flex items-center gap-1.5 bg-black/40 p-1 rounded-lg border border-white/5 self-start sm:self-auto">
              <button
                id="btn-format-bullets"
                type="button"
                onClick={() => setSummaryFormat("bullets")}
                className={`text-[9px] uppercase font-black px-2 py-1 rounded transition-all cursor-pointer ${
                  summaryFormat === "bullets" ? "bg-emerald-600 text-white" : "text-slate-400 hover:text-white"
                }`}
              >
                Bullets
              </button>
              <button
                id="btn-format-paragraph"
                type="button"
                onClick={() => setSummaryFormat("paragraph")}
                className={`text-[9px] uppercase font-black px-2 py-1 rounded transition-all cursor-pointer ${
                  summaryFormat === "paragraph" ? "bg-emerald-600 text-white" : "text-slate-400 hover:text-white"
                }`}
              >
                Paragraph
              </button>
            </div>
          </div>

          {activeClip.subtitles.length === 0 ? (
            <div className="p-3 bg-black/20 border border-amber-500/15 rounded-xl text-center">
              <p className="text-[10px] text-amber-300 font-medium">
                ⚠️ ASR Transcript Empty. Please click "Whisper Auto-Transcribe" first to populate speech text.
              </p>
            </div>
          ) : (
            <div className="space-y-2.5">
              <button
                id="btn-trigger-summarization"
                onClick={handleSummarizeTranscript}
                disabled={summarizing}
                className="w-full py-2 bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs rounded-xl transition-all shadow-md shadow-emerald-600/10 flex items-center justify-center gap-1.5 cursor-pointer disabled:bg-slate-800 disabled:text-slate-400"
              >
                {summarizing ? (
                  <>
                    <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                    <span>Analyzing ASR Dialogue with Gemini...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-3.5 h-3.5 text-amber-200" />
                    <span>Extract AI {summaryFormat === "bullets" ? "Talking Points" : "Summary"}</span>
                  </>
                )}
              </button>

              {generatedSummary && (
                <div className="p-3 bg-black/40 border border-white/10 rounded-xl space-y-2">
                  <div className="text-xs text-slate-200 font-medium whitespace-pre-line leading-relaxed selection:bg-indigo-500/30">
                    {generatedSummary}
                  </div>
                  
                  <div className="flex items-center gap-2 border-t border-white/5 pt-2">
                    <button
                      id="btn-copy-summary"
                      onClick={handleCopySummary}
                      className="text-[10px] font-bold text-slate-300 hover:text-white px-2.5 py-1 bg-white/5 hover:bg-white/10 border border-white/5 rounded transition-colors flex items-center gap-1"
                    >
                      {copiedSummary ? "Copied!" : "Copy Output"}
                    </button>
                    <button
                      id="btn-apply-summary"
                      onClick={handleApplySummary}
                      className="text-[10px] font-bold text-emerald-400 hover:text-emerald-300 px-2.5 py-1 bg-emerald-500/10 hover:bg-emerald-500/15 border border-emerald-500/20 rounded transition-colors"
                      title="Set this summary as the clip post description caption"
                    >
                      Apply as Post Caption
                    </button>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
